apiVersion: home.digi.dev/v1
kind: Home
metadata:
  name: Soda
  namespace: default
spec:
  control:
    mode: "Auto"
  mount:
    home.digi.dev/v1/rooms:
      default/livingRoom1:
        brightness: 70
        mode: "On"
        mount:
          home.digi.dev/v1/objects:
            - class: "Lamp"
              name: "Main Lamp 1"
            - class: "Heater"
              name: "Room Heater 1"
